### ISSUE TITLE
server offline error

### ISSUE THREAD

**Issue by yoopaan** [bit-ml/Private-Set-Intersection#3]
<img width="772" alt="Screen Shot 2022-01-25 at 6 35 15 PM" src="https://user-images.githubusercontent.com/38783332/150960934-63d7d6dd-60b4-4ea6-b354-5f22e32d86ad.png">

```
❯ python3 server_offline.py
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/paan/Documents/github/Private-Set-Intersection/server_offline.py", line 23, in <module>
    PRFed_server_set = server_prf_offline_parallel(server_set, server_point_precomputed)
  File "/Users/paan/Documents/github/Private-Set-Intersection/oprf.py", line 36, in server_prf_offline_parallel
    with Pool(number_of_processes) as p:
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/pool.py", line 212, in __init__
Traceback (most recent call last):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <module>
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    self._repopulate_pool()
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/pool.py", line 303, in _repopulate_pool
    exitcode = _main(fd, parent_sentinel)
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/pool.py", line 326, in _repopulate_pool_static
    exitcode = _main(fd, parent_sentinel)
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    prepare(preparation_data)
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
    w.start()
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/process.py", line 121, in start
    _fixup_main_from_path(data['init_main_from_path'])
    self._popen = self._Popen(self)
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    main_content = runpy.run_path(main_path,
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/runpy.py", line 265, in run_path
    main_content = runpy.run_path(main_path,
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/runpy.py", line 97, in _run_module_code
    return Popen(process_obj)
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    _run_code(code, mod_globals, init_globals,
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/runpy.py", line 87, in _run_code
    return _run_module_code(code, init_globals, run_name,
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/runpy.py", line 97, in _run_module_code
    super().__init__(process_obj)
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    exec(code, run_globals)
  File "/Users/paan/Documents/github/Private-Set-Intersection/server_offline.py", line 23, in <module>
    _run_code(code, mod_globals, init_globals,
    PRFed_server_set = server_prf_offline_parallel(server_set, server_point_precomputed)
    self._launch(process_obj)
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/runpy.py", line 87, in _run_code
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
  File "/Users/paan/Documents/github/Private-Set-Intersection/oprf.py", line 36, in server_prf_offline_parallel
    prep_data = spawn.get_preparation_data(process_obj._name)
    with Pool(number_of_processes) as p:
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/spawn.py", line 154, in get_preparation_data
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/context.py", line 119, in Pool
    exec(code, run_globals)
  File "/Users/paan/Documents/github/Private-Set-Intersection/server_offline.py", line 23, in <module>
    PRFed_server_set = server_prf_offline_parallel(server_set, server_point_precomputed)
  File "/Users/paan/Documents/github/Private-Set-Intersection/oprf.py", line 36, in server_prf_offline_parallel
    _check_not_importing_main()
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/pool.py", line 212, in __init__
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    with Pool(number_of_processes) as p:
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/context.py", line 119, in Pool
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
    self._repopulate_pool()
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/pool.py", line 303, in _repopulate_pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/pool.py", line 212, in __init__
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/pool.py", line 326, in _repopulate_pool_static
    self._repopulate_pool()
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/pool.py", line 303, in _repopulate_pool
    w.start()
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/process.py", line 121, in start
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/pool.py", line 326, in _repopulate_pool_static
    self._popen = self._Popen(self)
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    w.start()
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/process.py", line 121, in start
    super().__init__(process_obj)
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._popen = self._Popen(self)
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    self._launch(process_obj)
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/spawn.py", line 154, in get_preparation_data
    return Popen(process_obj)
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    _check_not_importing_main()
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    super().__init__(process_obj)
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
    self._launch(process_obj)
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/paan/Documents/github/Private-Set-Intersection/server_offline.py", line 23, in <module>
    PRFed_server_set = server_prf_offline_parallel(server_set, server_point_precomputed)
  File "/Users/paan/Documents/github/Private-Set-Intersection/oprf.py", line 36, in server_prf_offline_parallel
    with Pool(number_of_processes) as p:
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/pool.py", line 212, in __init__
    self._repopulate_pool()
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
^CTraceback (most recent call last):
  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    prepare(preparation_data)
    prepare(preparation_data)
    prepare(preparation_data)
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    _fixup_main_from_path(data['init_main_from_path'])
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/runpy.py", line 265, in run_path
    main_content = runpy.run_path(main_path,
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/runpy.py", line 265, in run_path
    main_content = runpy.run_path(main_path,
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/runpy.py", line 265, in run_path
    main_content = runpy.run_path(main_path,
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/runpy.py", line 97, in _run_module_code
    return _run_module_code(code, init_globals, run_name,
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/runpy.py", line 97, in _run_module_code
    return _run_module_code(code, init_globals, run_name,
    return _run_module_code(code, init_globals, run_name,
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/runpy.py", line 87, in _run_code
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/paan/Documents/github/Private-Set-Intersection/server_offline.py", line 3, in <module>
    _run_code(code, mod_globals, init_globals,
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/runpy.py", line 87, in _run_code
    from auxiliary_functions import coeffs_from_roots
  File "/Users/paan/Documents/github/Private-Set-Intersection/auxiliary_functions.py", line 2, in <module>
    exec(code, run_globals)
    import numpy as np
  File "/Users/paan/Documents/github/Private-Set-Intersection/server_offline.py", line 3, in <module>
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/site-packages/numpy/__init__.py", line 379, in <module>
    exec(code, run_globals)
  File "/Users/paan/Documents/github/Private-Set-Intersection/server_offline.py", line 3, in <module>
    from auxiliary_functions import coeffs_from_roots
    _run_code(code, mod_globals, init_globals,
  File "/Users/paan/Documents/github/Private-Set-Intersection/auxiliary_functions.py", line 2, in <module>
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/runpy.py", line 87, in _run_code
    import numpy as np
    from auxiliary_functions import coeffs_from_roots
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/site-packages/numpy/__init__.py", line 163, in <module>
  File "/Users/paan/Documents/github/Private-Set-Intersection/auxiliary_functions.py", line 2, in <module>
    exec(code, run_globals)
  File "/Users/paan/Documents/github/Private-Set-Intersection/server_offline.py", line 3, in <module>
    import numpy as np
    from auxiliary_functions import coeffs_from_roots
  File "/Users/paan/Documents/github/Private-Set-Intersection/auxiliary_functions.py", line 2, in <module>
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/site-packages/numpy/__init__.py", line 163, in <module>
    import numpy as np
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/site-packages/numpy/__init__.py", line 163, in <module>
    from . import ma
    from . import ma
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/site-packages/numpy/ma/__init__.py", line 42, in <module>
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/site-packages/numpy/ma/__init__.py", line 42, in <module>
    from . import ma
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/site-packages/numpy/ma/__init__.py", line 42, in <module>
    _mac_os_check()
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/site-packages/numpy/__init__.py", line 372, in _mac_os_check
    _ = polyfit(x, y, 2, cov=True)
  File "<__array_function__ internals>", line 5, in polyfit
    from . import core
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/site-packages/numpy/ma/core.py", line 24, in <module>
    from . import core
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/site-packages/numpy/ma/core.py", line 24, in <module>
    from . import core
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/site-packages/numpy/ma/core.py", line 7643, in <module>
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/site-packages/numpy/lib/polynomial.py", line 641, in polyfit
    import inspect
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/inspect.py", line 1038, in <module>
    import inspect
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/inspect.py", line 2742, in <module>
    lhs = vander(x, order)
  File "<__array_function__ internals>", line 5, in vander
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/site-packages/numpy/lib/twodim_base.py", line 588, in vander
    v = empty((len(x), N), dtype=promote_types(x.dtype, int))
    Arguments = namedtuple('Arguments', 'args, varargs, varkw')
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/collections/__init__.py", line 394, in namedtuple
KeyboardInterrupt
    exec(s, namespace)
  File "<string>", line 1, in <module>
    inner.__doc__ = doc_note(np.inner.__doc__,
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/site-packages/numpy/ma/core.py", line 126, in doc_note
KeyboardInterrupt
    class Signature:
KeyboardInterrupt
    notesplit = re.split(r'\n\s*?Notes\n\s*?-----', inspect.cleandoc(initialdoc))
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/inspect.py", line 641, in cleandoc
    margin = min(margin, indent)
KeyboardInterrupt
Traceback (most recent call last):
  File "server_offline.py", line 23, in <module>
    PRFed_server_set = server_prf_offline_parallel(server_set, server_point_precomputed)
  File "/Users/paan/Documents/github/Private-Set-Intersection/oprf.py", line 37, in server_prf_offline_parallel
    outputs = p.map(server_prf_offline, inputs_and_point)
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/pool.py", line 765, in get
    self.wait(timeout)
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/multiprocessing/pool.py", line 762, in wait
    self._event.wait(timeout)
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/Users/paan/miniconda3/envs/psi/lib/python3.8/threading.py", line 302, in wait
    waiter.acquire()
KeyboardInterrupt
```

**Comment by yoopaan** [comment]
@rtitiu

**Comment by hf-cure** [comment]
I'm having a similar issue. Any updates on how to solve this?  @mbolboceanu @MirunaRosca @rtitiu
